-- Remove Street Address for Privacy
-- Note: This might not be fully compliant with German Impressumspflicht (requires summonable address).

-- Update Impressum
UPDATE public.pages
SET 
    content = '{
        "de": "<h1>Impressum</h1><p><strong>Angaben gemäß § 5 TMG</strong></p><p>Hamza Karabulut<br>89269 Vöhringen<br>Deutschland</p><p><strong>Kontakt</strong><br>E-Mail: kontakt@kolaydugun.de</p><p><strong>Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV</strong><br>Hamza Karabulut<br>89269 Vöhringen</p><p><strong>Streitschlichtung</strong><br>Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit: <a href=\"https://ec.europa.eu/consumers/odr\" target=\"_blank\">https://ec.europa.eu/consumers/odr</a>.<br>Unsere E-Mail-Adresse finden Sie oben im Impressum.<br>Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p>",
        "en": "<h1>Imprint</h1><p><strong>Information according to § 5 TMG</strong></p><p>Hamza Karabulut<br>89269 Vöhringen<br>Germany</p><p><strong>Contact</strong><br>E-Mail: kontakt@kolaydugun.de</p><p><strong>Responsible for content according to § 55 Abs. 2 RStV</strong><br>Hamza Karabulut<br>89269 Vöhringen</p><p><strong>Dispute Resolution</strong><br>The European Commission provides a platform for online dispute resolution (OS): <a href=\"https://ec.europa.eu/consumers/odr\" target=\"_blank\">https://ec.europa.eu/consumers/odr</a>.<br>You can find our email address in the imprint above.<br>We are not willing or obliged to participate in dispute resolution proceedings before a consumer arbitration board.</p>",
        "tr": "<h1>Künye</h1><p><strong>§ 5 TMG uyarınca bilgiler</strong></p><p>Hamza Karabulut<br>89269 Vöhringen<br>Almanya</p><p><strong>İletişim</strong><br>E-posta: kontakt@kolaydugun.de</p><p><strong>§ 55 Abs. 2 RStV uyarınca içerikten sorumlu</strong><br>Hamza Karabulut<br>89269 Vöhringen</p><p><strong>Uyuşmazlık Çözümü</strong><br>Avrupa Komisyonu, çevrimiçi uyuşmazlık çözümü (OS) için bir platform sunmaktadır: <a href=\"https://ec.europa.eu/consumers/odr\" target=\"_blank\">https://ec.europa.eu/consumers/odr</a>.<br>E-posta adresimizi yukarıda bulabilirsiniz.<br>Bir tüketici hakem heyeti önünde uyuşmazlık çözümü prosedürlerine katılmaya istekli veya yükümlü değiliz.</p>"
    }'::jsonb
WHERE slug = 'impressum';

-- Update Datenschutz
UPDATE public.pages
SET 
    content = '{
        "de": "<h1>Datenschutzerklärung</h1><h2>1. Verantwortlicher</h2><p>Hamza Karabulut<br>89269 Vöhringen<br>E-Mail: kontakt@kolaydugun.de</p><h2>2. Allgemeine Informationen</h2><p>Beim Zugriff auf unsere Webseite werden technisch bedingt folgende Daten übermittelt:</p><ul><li>IP-Adresse</li><li>Browser-Informationen</li><li>Zugriffszeit</li><li>Besuchte Seiten</li></ul><p>Diese Daten können zu Sicherheitszwecken temporär verarbeitet werden.</p><h2>3. YouTube Videos</h2><p>Auf unserer Webseite können YouTube-Videos eingebunden sein. Beim Laden eines Videos wird Ihre IP-Adresse an Google/YouTube-Server übermittelt.</p><p>Google Datenschutzerklärung: <a href=\"https://policies.google.com/privacy\" target=\"_blank\">https://policies.google.com/privacy</a></p><h2>4. Google Analytics</h2><p>Wir verwenden Google Analytics zur Analyse des Webseitenverkehrs. Google verarbeitet Ihre IP-Adresse anonymisiert.</p><p>Google Datenschutzerklärung: <a href=\"https://policies.google.com/privacy\" target=\"_blank\">https://policies.google.com/privacy</a></p><h2>5. Supabase</h2><p>Registrierung, Login und Nachrichtensystem werden durch Supabase bereitgestellt. Verarbeitete Daten:</p><ul><li>E-Mail</li><li>Passwort (gehasht)</li><li>Profildaten</li><li>Nachrichteninhalte</li></ul><p>Supabase Datenschutzerklärung: <a href=\"https://supabase.com/privacy\" target=\"_blank\">https://supabase.com/privacy</a></p><h2>6. PayPal</h2><p>Zahlungen können über PayPal abgewickelt werden. Dabei verarbeitet PayPal Nutzerdaten.</p><p>PayPal Datenschutzerklärung: <a href=\"https://www.paypal.com/de/webapps/mpp/ua/privacy-full\" target=\"_blank\">https://www.paypal.com/de/webapps/mpp/ua/privacy-full</a></p><h2>7. Nutzerrechte</h2><p>Nutzer haben das Recht auf:</p><ul><li>Auskunft</li><li>Löschung</li><li>Berichtigung</li></ul><p>Kontakt: kontakt@kolaydugun.de</p><h2>8. Speicherdauer</h2><p>Bei Kontolöschung werden Nutzerdaten technisch entfernt. Server-Logs werden nur kurzzeitig gespeichert.</p>",
        "en": "<h1>Privacy Policy</h1><h2>1. Controller</h2><p>Hamza Karabulut<br>89269 Vöhringen<br>E-Mail: kontakt@kolaydugun.de</p><h2>2. General Information</h2><p>When accessing our website, the following data is transmitted technically:</p><ul><li>IP Address</li><li>Browser Information</li><li>Access Time</li><li>Visited Pages</li></ul><p>This data may be processed temporarily for security purposes.</p><h2>3. YouTube Videos</h2><p>YouTube videos may be embedded on our website. When loading a video, your IP address is transmitted to Google/YouTube servers.</p><p>Google Privacy Policy: <a href=\"https://policies.google.com/privacy\" target=\"_blank\">https://policies.google.com/privacy</a></p><h2>4. Google Analytics</h2><p>We use Google Analytics to analyze website traffic. Google processes your IP address anonymously.</p><p>Google Privacy Policy: <a href=\"https://policies.google.com/privacy\" target=\"_blank\">https://policies.google.com/privacy</a></p><h2>5. Supabase</h2><p>Registration, login, and messaging system are provided by Supabase. Processed data:</p><ul><li>Email</li><li>Password (hashed)</li><li>Profile Data</li><li>Message Content</li></ul><p>Supabase Privacy Policy: <a href=\"https://supabase.com/privacy\" target=\"_blank\">https://supabase.com/privacy</a></p><h2>6. PayPal</h2><p>Payments can be processed via PayPal. PayPal processes user data during this process.</p><p>PayPal Privacy Policy: <a href=\"https://www.paypal.com/de/webapps/mpp/ua/privacy-full\" target=\"_blank\">https://www.paypal.com/de/webapps/mpp/ua/privacy-full</a></p><h2>7. User Rights</h2><p>Users have the right to:</p><ul><li>Information</li><li>Deletion</li><li>Correction</li></ul><p>Contact: kontakt@kolaydugun.de</p><h2>8. Storage Duration</h2><p>User data is technically removed upon account deletion. Server logs are stored only briefly.</p>",
        "tr": "<h1>Gizlilik Politikası</h1><h2>1. Sorumlu</h2><p>Hamza Karabulut<br>89269 Vöhringen<br>E-posta: kontakt@kolaydugun.de</p><h2>2. Genel Bilgi</h2><p>Web sitesine erişildiğinde tarayıcı tarafından teknik olarak aşağıdaki veriler iletilir:</p><ul><li>IP Adresi</li><li>Tarayıcı Bilgisi</li><li>Erişim Zamanı</li><li>Ziyaret Edilen Sayfalar</li></ul><p>Bu veriler sunucu güvenliği için geçici olarak işlenebilir.</p><h2>3. YouTube Videoları</h2><p>Web sitesinde YouTube videoları embed edilmiş olabilir. Video yüklendiğinde IP adresi Google/YouTube sunucularına iletilir.</p><p>Google Gizlilik Politikası: <a href=\"https://policies.google.com/privacy\" target=\"_blank\">https://policies.google.com/privacy</a></p><h2>4. Google Analytics</h2><p>Site trafiğini analiz etmek için Google Analytics kullanılabilir. Google IP adresini anonimleştirerek işler.</p><p>Google Gizlilik Politikası: <a href=\"https://policies.google.com/privacy\" target=\"_blank\">https://policies.google.com/privacy</a></p><h2>5. Supabase</h2><p>Kayıt, giriş ve mesaj sistemi Supabase tarafından sağlanır. İşlenen veriler:</p><ul><li>E-posta</li><li>Şifre (hashed)</li><li>Profil Verileri</li><li>Mesaj İçerikleri</li></ul><p>Supabase Gizlilik Politikası: <a href=\"https://supabase.com/privacy\" target=\"_blank\">https://supabase.com/privacy</a></p><h2>6. PayPal</h2><p>Ödemeler PayPal üzerinden alınabilir. Bu işlem sırasında PayPal kullanıcı verilerini işler.</p><p>PayPal Gizlilik Politikası: <a href=\"https://www.paypal.com/de/webapps/mpp/ua/privacy-full\" target=\"_blank\">https://www.paypal.com/de/webapps/mpp/ua/privacy-full</a></p><h2>7. Kullanıcı Hakları</h2><p>Kullanıcılar şunları talep edebilir:</p><ul><li>Bilgi alma</li><li>Silinme</li><li>Düzeltme</li></ul><p>İletişim: kontakt@kolaydugun.de</p><h2>8. Saklama Süresi</h2><p>Hesap silindiğinde kullanıcı verileri teknik olarak kaldırılır. Sunucu logları kısa süre saklanır.</p>"
    }'::jsonb
WHERE slug = 'datenschutz';
