export const CATEGORIES = [
    'Wedding Venues',
    'Bridal Fashion',
    'Hair & Make-Up',
    'Groom Suits',
    'Wedding Cakes',
    'Wedding Planners',
    'Wedding Cars',
    'Catering & Party Service',
    'Wedding Speakers (Trauredner)',
    'Flowers & Decoration',
    'Invitations & Stationery',
    'Wedding Rings',
    'Wedding Photography',
    'Wedding Videography',
    'Photobox',
    'DJs',
    'Musicians',
    'Entertainment'
];

export const getCategoryTranslationKey = (category) => {
    const mapping = {
        'Wedding Venues': 'wedding_venues',
        'Bridal Fashion': 'bridal_fashion',
        'Hair & Make-Up': 'hair_makeup',
        'Groom Suits': 'groom_suits',
        'Wedding Cakes': 'wedding_cakes',
        'Wedding Planners': 'wedding_planners',
        'Wedding Cars': 'wedding_cars',
        'Catering & Party Service': 'catering_party',
        'Wedding Speakers (Trauredner)': 'wedding_speakers',
        'Flowers & Decoration': 'flowers_decoration',
        'Invitations & Stationery': 'invitations_stationery',
        'Wedding Rings': 'wedding_rings',
        'Wedding Photography': 'wedding_photography',
        'Wedding Videography': 'wedding_videography',
        'Photobox': 'photobox',
        'DJs': 'djs',
        'Musicians': 'musicians',
        'Entertainment': 'entertainment'
    };
    return mapping[category] || category.toLowerCase().replace(/\s+/g, '_');
};

export const CITIES = [
    'Berlin',
    'Hamburg',
    'München (Munich)',
    'Köln (Cologne)',
    'Frankfurt am Main',
    'Stuttgart',
    'Düsseldorf',
    'Dortmund',
    'Essen',
    'Bremen',
    'Hannover',
    'Leipzig',
    'Dresden',
    'Nürnberg (Nuremberg)',
    'Duisburg',
    'Bochum',
    'Wuppertal',
    'Bielefeld',
    'Bonn',
    'Münster',
    'Karlsruhe',
    'Mannheim',
    'Wiesbaden',
    'Augsburg',
    'Mönchengladbach',
    'Gelsenkirchen',
    'Braunschweig',
    'Kiel',
    'Aachen',
    'Chemnitz',
    'Magdeburg',
    'Freiburg im Breisgau',
    'Krefeld',
    'Lübeck',
    'Oberhausen',
    'Erfurt',
    'Mainz',
    'Rostock',
    'Kassel',
    'Hagen',
    'Saarbrücken',
    'Hamm',
    'Potsdam',
    'Ludwigshafen',
    'Oldenburg',
    'Leverkusen',
    'Osnabrück',
    'Solingen',
    'Heidelberg',
    'Herne',
    'Ulm',
    'Regensburg'
];
